[package]
name = "tui-equalizer"
description = "An equalizer widget for Ratatui with multiple frequency bands."
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
derive_builder = "0.20"
ratatui = { version = "0.29", default-features = false }

[dev-dependencies]
color-eyre = "0.6.3"
crossterm = "0.28.1"
itertools = "0.14.0"
rand = "0.9.0"
ratatui = "0.29.0"
